<h1>Adresse</h1>
<p>Veuillez saisir vos informations de livraison.</p>
<form class="address-form" method="post">
    <div>
        <label for="street">N° et nom de rue</label>
        <input type="string" id="street" name="street" required>
    </div>
    <div>
        <label for="postal-code">Code postal</label>
        <input type="number" id="postal-code" name="postal-code" required>
    </div>
    <div>
        <label for="town">Ville</label>
        <input type="string" id="town" name="town" required>
    </div>
    <div>
        <label for="country">Pays</label>
        <input type="string" id="country" name="country" required>
    </div>
    <?php if (!empty($message)): ?>
        <p><?= htmlspecialchars($message) ?></p>
    <?php endif; ?>
    <button type="submit" class="btn">Confirmer</button>
</form>

