<?php var_dump($orders);
?>

<h1>Dashboard</h1>

<nav>
    <!-- <button class="btn" onClick={()=> setOnglet(1)}>Liste des commandes</button>
    <button class="btn" onClick={()=> setOnglet(2)}>Liste des thés</button>
    <button class="btn" onClick={()=> setOnglet(3)}>Ajouter un thé</button> -->
    <button class="btn" onclick="displaySection(0)">Liste des commandes</button>
    <button class="btn" onclick="displaySection(1)">Liste des thés</button>
    <button class="btn" onclick="displaySection(2)">Ajouter un thé</button>
</nav>



<section id="orders" style='display:none'>
    <h2>Les commandes</h2>
    <p>
        Filtrer par
        <select name="filter" id="filter-select">
            <option value="all">Toutes</option>
            <option value="unprocessed">Non traitées</option>
            <option value="processed">Traitées</option>
        </select>
    </p>
    <table>
        <thead>
            <tr>
                <th>Numéro de commande</th>
                <th>Date</th>
                <th>Nom du client</th>
                <th>Montant total</th>
                <th>Traitée</th>
                <th></th>
            </tr>

        </thead>
        <tbody id="orders-list">
            <!-- {orders.map((order, i) => { -->
            <!-- {(filtre == 'toutes' || filtre == order.statut) && -->
        <?php 
            foreach($orders as $order): ?>
            <tr key={i}>
                <td><?= htmlspecialchars($order['id']) ?></td>
                <td><?= (new DateTime(htmlspecialchars($order['date']), new DateTimeZone('Europe/Paris')))->format('Y-m-d H:i:s'); ?></td>           
                <td><?= htmlspecialchars($order['name']) . " " . htmlspecialchars($order['last_name']) ?></td>
                <td><?= htmlspecialchars(number_format((float)$order['total'], 2, '.', '')) ?> €</td>
<!-- TODO : format strings in another file ? -->
                <td>
                    <form id="statusForm" method="POST">
                        <!-- TODO : remplacer sayHello() par updateStatus(index) -->
                        <!-- <input type="checkbox" class="orderStatus" name="status" <?= $order['status'] == 1 ? "checked" : ""; ?> onchange=sayHello() > -->
                        <input type="checkbox" class="orderStatus" name="status" <?= $order['status'] == 1 ? "checked" : ""; ?> onchange="updateStatus(<?= $order['id'] ?>)" >
                        <input type="hidden" name="orderId" >
                    </form>
                </td>
                <td><button onclick="showDetails(<?=$order['id']?>)" class="btn">Voir le détail</button></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</section>

<section id="order-details">
</section>



<!-- <?php var_dump($teas); 
// $tea = $teas[0]; ?> -->


<section id="teas" style='display:none'>
    <!-- All Teas -->
    <h2>Les thés</h2>
    <table>
        <thead>
            <tr>
                <th>Image</th>
                <th>Nom</th>
                <th>Catégorie</th>
                <th></th>
            </tr>

        </thead>
        <tbody>
            <?php foreach($teas as $tea): ?>
            <tr>
                <!-- <td><img style={{ maxWidth:'80px' }} src={'img/'+tea.image} /></td> -->
                <td><img style="max-width: 80px" src="public/img/tea/<?= $tea['category_id'] ?>" /></td>
                <!-- <td><img style="max-width:80px" src="public/img/tea/1.jpg" /></td> -->
                <td><?= htmlspecialchars($tea['name']) ?></td>
                <td><?= htmlspecialchars($tea['catName']) ?></td>
                <td>
                    <button className="btn">Modifier</button>
                    <button className="btn">Supprimer</button>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</section>



<!-- <?php var_dump($cats);?> -->

<section id="add-tea">
    
    <h2>Ajouter un thé</h2>
    <!-- TODO : why script can't be recognized after the form ? -->

    <!-- <form id="add" encType="multipart/form-data"> -->
    <!-- <form id="add" method="POST" action="/cup_of_tea_php/?route=add-tea"> -->
    <form id="add" method="POST" enctype="multipart/form-data">
        <!-- TODO : maybe automatically prefill according to the database . (ref = REF{lastref + 1}) -->
        <div>
            <label htmlFor="ref">Référence</label>
            <input type="text" id="ref" name='ref' placeholder="REF0001" onChange="" />
        </div>
        <div>
            <label htmlFor="cat">Catégorie</label>
            <select id="cat" name="cat" placeholder="Thé noir" onChange="">
                <!-- {
                cats.map((cat, i) => <option key={i} value={cat.id}>{cat.nom}</option>)
                } -->
                <?php foreach($cats as $cat): ?>
                    <option value=<?= htmlspecialchars($cat['id']) ?>><?= htmlspecialchars($cat['name']) ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <div>
            <label htmlFor="name">Nom du thé</label>
            <input type="text" id="name" name="name" placeholder="Thé Vert Matcha" onChange="" />
        </div>
        <div>
            <label htmlFor="subtitle">Sous-titre</label>
            <textarea id="subtitle" name="subtitle" placeholder="Pur et Puissant" onChange=""></textarea>
        </div>
        <div>
            <label htmlFor="description">Description</label>
            <textarea id="description" name="description" placeholder="Le matcha offre un goût riche et une couleur éclatante." onChange=""></textarea>
        </div>
        <!-- TODO : ajouter la colonne stock dans la table tea -->
        <!-- <div>
            <label htmlFor="stock">Stock</label>
            <input type="text" id="stock" name="stock" value={stock} onChange="" />
        </div> -->
        <div>
            <label htmlFor="image">Image</label>
            <input type="file" id="image" name="image" />
        </div>
        <div>
            <label htmlFor="favorite">
                <input type="checkbox" id="favorite" name="favorite" onchange="" />
                Coup de coeur</label>
        </div>
        <div>
            <!-- <button type="submit" onclick=sayHello() class="btn">Ajouter</button> -->
            <button type="button" onclick=addTea() class="btn">Ajouter</button>
        </div>
    </form>

<button onclick=addTea()>push</button>
</section>



<script src="/cup_of_tea_php/public/js/admin.js"></script>












