<div class="center-container">
<h1>Mon panier</h1>

<p id="empty-message"><?php if (empty($cart)): ?>Le panier est vide.<?php endif; ?></p>
<?php if (!empty($cart)): ?>

<?php if (empty($cart)): ?>
    <p>Le panier est vide.</p>
<?php else: ?>
    <table id="cart-table">
        <thead>
            <tr>
                <th></th>
                <th>Produit</th>
                <th>Format</th>
                <th>Quantité</th>
                <th>Prix Unit.</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total = 0;
            $index = 0;
            foreach ($cart as $teaId => $tea): ?>
                <?php foreach ($tea['formats'] as $formatId => $format): ?>
                    <tr>
                        <td><?= ++$index ?></td>
                        <td><?= htmlspecialchars($tea['name']) ?></td>
                        <td><?= htmlspecialchars($format['format']) ?></td>
                        <td>
                            <select name="quantity-select" onchange="changeQuantity(<?= $teaId ?>, <?= $formatId ?>, this.value)">
                                <?php for($i = 1; $i <= 10; $i++): ?>
                                    <option value="<?= $i ?>" <?= $i == $format['quantity'] ? 'selected' : '' ?>><?= $i ?></option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td><?= number_format(htmlspecialchars($format['price']), 2) ?>€</td>
                        <td><?= number_format(htmlspecialchars($format['quantity'] * $format['price']), 2) ?>€</td>
                        <td><button class="btn grey-btn" onclick="changeQuantity(<?= $teaId ?>, <?= $formatId ?>, 0)">X</button></td>
                    </tr>
                <?php 
                $total += $format['price'] * $format['quantity'];
                endforeach; ?>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr class='total'>
                <td colspan='5'></td>
                <td><?= number_format($total, 2) ?>€</td>
            </tr>
        </tfoot>
    </table>
<?php endif; ?>

<br>

<a href="address" class="btn">Valider la sélection</a>
</div>
<?php endif; ?>
</div>

<script src="public/js/cart.js"></script>
