<h1>Créer un compte</h1>
{message != "" &&
<p>{message}</p>}
<!-- TODO changer l'id -->
<form id="cr">
    <div>
        <label htmlFor="nom">Votre nom</label>
        <input type="text" id="nom" value={nom} onChange={handleChange} />
    </div>
    <div>
        <label htmlFor="prenom">Votre prénom</label>
        <input type="text" id="prenom" value={prenom} onChange={handleChange} />
    </div>
    <div>
        <label htmlFor="email">Votre email</label>
        <input type="email" id="email" value={email} onChange={handleChange} />
    </div>
    <div>
        <label htmlFor="password">Votre mot de passe</label>
        <input type="password" id="password" value={password} onChange={handleChange} />
    </div>
    <button className="btn" type="button" onClick={submit}>
        Créer un compte
    </button>
</form>
<p>
    <a href="/connexion">J'ai déjà un compte</a>
</p>