<section id="christmas">
    <h1>C'est noël chez Cup of Tea, profitez-en !</h1>
    <img src="public/img/offre-noel.jpg" alt="Offre spéciale pour noel ! Dès 45€ d'achat, le photophore de noël vous sera offert. Et dès 85€ un thé vert au prune et coing de 100 gramme vous sera offert" />
    <br>
    <small>Pour toute commande effectuée avant le 20 décembre</small>
</section>
<section id="slider">
    <div class="css-slider-wrapper">
        <input type="radio" name="slider" class="slide-radio1" checked id="slider_1">
        <input type="radio" name="slider" class="slide-radio2" id="slider_2">

        <div class="slider-pagination">
            <label for="slider_1" class="page1"></label>
            <label for="slider_2" class="page2"></label>
        </div>

        <div class="slider-content">
            <div class="slider-inner">
                <div class="slide slide1">
                    <img src="public/img/slider/1.jpg" alt="Retrouvez toute nos idées cadeaux pour les fêtes de noël">
                </div>
                <div class="slide slide2">
                    <img src="public/img/slider/2.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée">
                </div>
            </div>
        </div>
    </div>
</section>
<section id="categories">
    <h2>
        <span>Choisissez votre thé</span>
    </h2>
    <a href="#">
        <img src="public/img/tea/1.jpg" alt="Tasse de thé noir" />
        <h3>Thé noir</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/2.jpg" alt="Tasse de thé vert" />
        <h3>Thé vert</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/3.jpg" alt="Tasse de oolong" />
        <h3>Oolong</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/4.jpg" alt="Tasse de thé blanc" />
        <h3>Thé blanc</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/5.jpg" alt="Tasse de rooibos" />
        <h3>Rooibos</h3>
    </a>
</section>
<section id="tea">
    <article class="tea-card" id="new">
        <h2>
            <span>Notre nouveauté</span>
        </h2>

        <img src="public/img/<?=  htmlspecialchars($latest['image']) ?>" alt="<?=  htmlspecialchars($latest['name']) ?>" />

        <h3><?=  htmlspecialchars($latest['name']) ?></h3>

        <p><?=  htmlspecialchars($latest['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($latest['price']) ?> €</strong>
            </p>
        </section>
            
        <a class="btn" href="tea/<?= htmlspecialchars($latest['id']) ?>">
            Voir ce produit
        </a>
    </article>
    <article class="tea-card" id="best">
        <h2>
            <span>Notre best-seller</span>
        </h2>
        <img src="public/img/<?=  htmlspecialchars($bestseller['image']) ?>" alt="<?=  htmlspecialchars($bestseller['name']) ?>" />
        <h3><?=  htmlspecialchars($bestseller['name']) ?></h3>

        <p><?=  htmlspecialchars($bestseller['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($bestseller['price']) ?> €</strong>
            </p>
        </section>
        <a class="btn" href="tea/<?= htmlspecialchars($bestseller['id']) ?>">
            Voir ce produit
        </a>
    </article>
    <article class="tea-card" id="crush">
        <h2>
            <span>Notre coup de coeur</span>
        </h2>
        <img src="public/img/<?=  htmlspecialchars($favorite['image']) ?>" alt="<?=  htmlspecialchars($favorite['name']) ?>" />
        <h3><?=  htmlspecialchars($favorite['name']) ?></h3>

        <p><?=  htmlspecialchars($favorite['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($favorite['price']) ?> €</strong>
            </p>
        </section>
        <a class="btn" href="tea/<?= htmlspecialchars($favorite['id']) ?>">
            Voir ce produit
        </a>
    </article>
</section>