<section id="noel">
    <h1>C'est noël chez Cup of Tea, profitez-en !</h1>
    <img src="public/img/offre-noel.jpg" alt="Offre spéciale pour noel ! Dès 45€ d'achat, le photophore de noël vous sera offert. Et dès 85€ un thé vert au prune et coing de 100 gramme vous sera offert" />
    <!-- AJOUT de br -->
    <br>
    <small>Pour toute commande effectuée avant le 20 décembre</small>
</section>
<section id="slider">
    <div class="flexslider">
        <ul class="slides">
            <li>
                <img src="public/img/slider/1.jpg" alt="Retrouvez toute nos idées cadeaux pour les fêtes de noël" />
            </li>
            <li>
                <img src="public/img/slider/2.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée" />
            </li>
        </ul>
    </div>
</section>
<section id="categorie">
    <h2>
        <span>Choisissez votre thé</span>
    </h2>
    <a href="#">
        <img src="public/img/tea/1.jpg" alt="Tasse de thé noir" />
        <h3>Thé noir</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/2.jpg" alt="Tasse de thé vert" />
        <h3>Thé vert</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/3.jpg" alt="Tasse de oolong" />
        <h3>Oolong</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/4.jpg" alt="Tasse de thé blanc" />
        <h3>Thé blanc</h3>
    </a>
    <a href="#">
        <img src="public/img/tea/5.jpg" alt="Tasse de rooibos" />
        <h3>Rooibos</h3>
    </a>
</section>
<section id="tea">
    <article id="new">
        <h2>
            <span>Notre nouveauté</span>
        </h2>
        <!-- <img src="/img/" + nouveaute.image alt=nouveaute.nom /> -->
        <!-- <img src="public/img/tea/1.jpg" alt="Tasse de thé noir" /> -->
        <img src="public/img/tea/<?=  htmlspecialchars($latest['category_id']) ?>.jpg" alt="<?=  htmlspecialchars($latest['name']) ?>" />
        <!-- <h3>{ nouveaute.nom }</h3> -->
        <!-- <h3>Tasse de thé noir</h3> -->
        <h3><?=  htmlspecialchars($latest['name']) ?></h3>

        <p><?=  htmlspecialchars($latest['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($latest['price']) ?> €</strong>
            </p>
        </section>
        <!-- <a class="btn" href={"/tea/"+nouveaute.id}> -->
        <a class="btn" href="public/img/tea/2.jpg">
        <!-- <a class="btn" href="http://localhost/cup_of_tea_php/?route=tea&tea_id=2"> -->
            Voir ce produit
        </a>
    </article>
    <article id="best">
        <h2>
            <span>Notre best-seller</span>
        </h2>
        <img src="public/img/tea/<?=  htmlspecialchars($bestseller['category_id']) ?>.jpg" alt="<?=  htmlspecialchars($bestseller['name']) ?>" />
        <!-- <img src="public/img/tea/4.jpg" alt="Tasse de thé blanc" /> -->
        <h3><?=  htmlspecialchars($bestseller['name']) ?></h3>

        <p><?=  htmlspecialchars($bestseller['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($bestseller['price']) ?> €</strong>
            </p>
        </section>
        <a class="btn" href="public/img/tea/3.jpg">
            Voir ce produit
        </a>
    </article>
    <article id="crush">
        <h2>
            <span>Notre coup de coeur</span>
        </h2>
        <!-- <img src={ "/img/" + coupDeCoeur.image } alt={ coupDeCoeur.nom } /> -->
        <img src="public/img/tea/<?=  htmlspecialchars($favorite['category_id']) ?>.jpg" alt="<?=  htmlspecialchars($favorite['name']) ?>" />
        <!-- <img src="public/img/tea/4.jpg" alt="Tasse de thé blanc" /> -->
        <h3><?=  htmlspecialchars($favorite['name']) ?></h3>

        <p><?=  htmlspecialchars($favorite['subtitle']) ?></p>
        <section class="price">
            <p>
                À partir de <strong><?=  htmlspecialchars($favorite['price']) ?> €</strong>
            </p>
        </section>
        <a class="btn" href="public/img/tea/4.jpg">
            Voir ce produit
        </a>
    </article>
</section>