<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <base href="http://localhost/cup_of_tea_php/" />
    <link rel="icon" href="public/img/title.png" />
    <title>Votre Application</title>
    <link rel="stylesheet" href="/cup_of_tea_php/public/css/base.css">
    <link rel="stylesheet" href="/cup_of_tea_php/public/css/font-awesome.min.css">
    <link rel="stylesheet" href="/cup_of_tea_php/public/css/normalize.css">
    <link rel="stylesheet" href="/cup_of_tea_php/public/css/style.css">
</head>


<body>
<?php 
// var_dump($_SESSION['cart']); 
// var_dump(isset($_SESSION['user_id']) ? $_SESSION['user_id'] : "no user id"); 
?>

  <!-- TODO : where place scripts ? -->
  <header>
    <img class="ribbon" src="public/img/ribbon.svg" alt="élu meilleur thé en 2016" />
    <section id="topbar">Livraison offerte à partir de 65€ d'achat !</section>
    <div class="container">
      <section id="logo">
        <a href="/cup_of_tea_php/home">
          <img src="public/img/logo.png" alt="Logo de Cup of Tea" />
        </a>
        <section style="display:<?= isset($cart)? 'block' : 'none' ?>" id="cart">
          <?php if(isset($cart)) require_once $cart; ?>
        </section>
      </section>
      <nav>
        <!-- <a href="/teas">Thés</a> -->
        <a href="/cup_of_tea_php/teas">Thés</a>
        <a href="/cup_of_tea_php/about">Notre histoire</a>
        <?php if(isset($_SESSION['is_admin']) && $_SESSION['is_admin'] == 1): ?>
         <a href="/cup_of_tea_php/admin">Admin</a>
       <?php endif ?>
        <?php if(!isset($_SESSION['user_id'])): ?>
          <a href="/cup_of_tea_php/login">Me connecter</a>
        <?php elseif($_GET['route'] == 'my-account'): ?>
          <a href="/cup_of_tea_php/logout">Me déconnecter</a>
        <?php else: ?>
          <a href="/cup_of_tea_php/my-account">Mon compte</a>
         <?php endif ?>
      </nav>
    </div>
          
  </header>
        
  <main class="container">
    <?php require_once $template; ?>
  </main>
        
    <footer>
      <section id="info">
        <article>
        <i class="fa fa-lock"></i>
        <small>Paiement sécurisé</small>
      </article>
      <article>
        <i class="fa fa-truck"></i>
        <small>Ma livraison offerte</small>
      </article>
      <article>
        <i class="fa fa-money"></i>
        <small>Carte de fidélité</small>
      </article>
      <article>
        <i class="fa fa-phone"></i>
        <small>Service client</small>
      </article>
      <article>
        <i class="fa fa-check-circle"></i>
        <small>Garantie qualité</small>
      </article>
    </section>
    <section id="bottombar">
      <article>
        <h2>Découvrir Cup of Tea</h2>
        <ul>
          <li>Notre histoire</li>
            <li>Nos boutiques</li>
            <li>Le Thé de A à Z</li>
            <li>Espace clients professionnels</li>
            <li>Recrutement</li>
            <li>Contactez-nous !</li>
            <li>L'École du Thé</li>
        </ul>
      </article>
      <article>
        <h2>Commandez en ligne</h2>
        <ul>
          <li>Première visite</li>
            <li>Aide - FAQ</li>
            <li>Service client</li>
            <li>Suivre ma commande</li>
            <li>Conditions générales de vente</li>
            <li>Informations légales</li>
        </ul>
      </article>
      <article>
        <h2>Suivez-nous !</h2>
        <ul>
          <li>Notre histoire</li>
            <li>Nos boutiques</li>
            <li>Le Thé de A à Z</li>
            <li>Espace clients professionnels</li>
        </ul>
      </article>
    </section>
  
  </footer>

</body>

</html>