<h1>Connexion</h1>
<!-- <p style={{ color:'red' }}>{message}</p> -->
<p style="color:red">{message}</p>
<form>
    <div>
        <label htmlFor="email">Votre email</label>
        <input type="email" id="email" value={email} onChange={changeEmail} />
    </div>
    <div>
        <label htmlFor="password">Votre mot de passe</label>
        <input type="password" id="password" value={password} onChange={changePassword} />
    </div>
    <button className="btn" type="button" onClick={submit}>Se connecter</button>
</form>
<p>
    <a href="/cup_of_tea_php/?route=create-account">Je n'ai pas encore de compte</a>
</p>