<div class="center-container">
<h1>Connexion</h1>
<form id="loginForm" method="POST">
    <div>
        <label for="email">Votre email</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="password">Votre mot de passe</label>
        <input type="password" id="password" name="password" required />
    </div>
    <?php if (!empty($errorMessage)): ?>
        <p style="color:red" class="error" id="message"><?= htmlspecialchars($errorMessage) ?></p>
    <?php endif; ?>
    <button class="btn" type="submit">Se connecter</button>
</form>
<p>
    <a href="signup">Je n'ai pas encore de compte</a>
</p>
</div>