<h1>Connexion</h1>
<!-- <p style="color:red" id="message"></p> -->
<?php if (!empty($errorMessage)): ?>
    <p style="color:red" id="message"><?= htmlspecialchars($errorMessage) ?></p>
<?php endif; ?>
<form id="loginForm" method="POST">
    <div>
        <label for="email">Votre email</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="password">Votre mot de passe</label>
        <input type="password" id="password" name="password" required />
    </div>
    <button class="btn" type="submit">Se connecter</button>
</form>
<p>
    <a href="http://localhost/cup_of_tea_php/?route=signup">Je n'ai pas encore de compte</a>
</p>