<h1>Mon compte</h1>

<h2><span>Mes informations</span></h2>
<form method="POST">
    <div>
        <label htmlFor="last-name">Nom</label>
        <input type="text" id="last-name" name="last-name" value=<?= htmlspecialchars($user['last_name']) ?> disabled onChange={handleChange} />
    </div>

    <div>
        <label htmlFor="name">Prénom</label>
        <input type="text" id="name" name="name" value=<?= htmlspecialchars($user['name']) ?> disabled />
    </div>

    <div>
        <label htmlFor="email">Email</label>
        <input type="email" id="email" name="email" value=<?= htmlspecialchars($user['email']) ?> disabled />
    </div>

    <div>
        <label htmlFor="old-password">Ancien mot de passe</label>
        <input type="password" id="old-password" name="old-password" disabled />
    </div>

    <div>
        <label htmlFor="new-password">Nouveau mot de passe</label>
        <input type="password" id="new-password" name="new-password" disabled />
    </div>
    <?php if (!empty($message)): ?>
        <p id="message"><?= htmlspecialchars($message) ?></p>
    <?php endif; ?>
        <button id="enable-change-btn" class="btn" type="button" onclick="enableChange()">Modifier</button>
        <button id="change-btn" class="btn" type="submit" style="display:none">Valider les modifications</button>
    </form>
    
    <h2><span>Mes commandes</span></h2>
<div class="flex">  
    <?php if(count($orders) > 0): ?>
    <table id="past-orders">
        <thead>
            <tr>
                <th></th>
                <th>Date de la commande</th>
                <th>Montant de la commande</th>
                <th>Détail</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $index = 0;
            foreach($orders as $order): ?>
            <tr>
                <td><?= count($orders) - $index ?></td>
                <td><?= $order['date'] ?></td>
                <td><?= number_format($order['total'], 2) ?> €</td>
                <td><button class="detail-btn" onclick="showDetail(<?= $index . ', ' . $order['id'] ?>)"><i class="fa fa-eye"></i></button></td>
            </tr>
            <?php
            $index++;
            endforeach ?>
        </tbody>
        
    </table>
    <?php else: ?>
        <div>Vous n'avez pas encore passé de commande.</div>
    <?php endif ?>
</div>

<script src="public/js/myAccount.js"></script>