<h1>Mon compte</h1>

<h2>Mes informations</h2>
<form>
            <div>
                <label htmlFor="nom">Nom</label>
                <input type="text" id="nom" value={nom} disabled={dis} onChange={handleChange} />
            </div>

            <div>
                <label htmlFor="prenom">Prénom</label>
                <input type="text" id="prenom" value={prenom} disabled={dis} onChange={handleChange} />
            </div>

            <div>
                <label htmlFor="email">Email</label>
                <input type="email" id="email" value={email} disabled={dis} onChange={handleChange} />
            </div>

            <div>
                <label htmlFor="password">Votre mot de passe</label>
                <input
                    type="password"
                    id="password"
                    value={password}
                    onChange={handleChange}
                />
            </div>
            {/* si il y a un message alors on l'affiche*/}
            { message != "" && 
                <p>{message}</p>
            }
            <button type="button" onClick={modifier}>{ dis==true ? 'Modifier':'Valider les modifications'}</button>
        </form>


<h2>Mes commandes</h2>
<div class="flex">  
    <table class="commande">
        <thead>
            <tr>
                <th>Numéro de commande</th>
                <th>Date de la commande</th>
                <th>Montant de la commande</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {
            orders.map((order, i) => {
            return(
            <tr key={i}>
                <td>{order.id}</td>
                <td>{new Date(order.date).toLocaleDateString()}</td>
                <td>{order.total.toFixed(2)} €</td>
                <td><button data-id={order.id} onClick={details}><i class="fa fa-eye"></i></button></td>
            </tr>)
            })
            }
        </tbody>

    </table>
    {id != 0 &&
    <DetailOrder id={id} />
    }
</div>