<div class="center-container">
<h1>Créer un compte</h1>
<form id="signupForm" method="POST">
    <div>
        <label for="last_name">Votre nom</label>
        <input type="text" id="last_name" name="last_name" required />
    </div>
    <div>
        <label for="name">Votre prénom</label>
        <input type="text" id="name" name="name" required />
    </div>
    <div>
        <label for="email">Votre email</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="password">Votre mot de passe</label>
        <input type="password" id="password" name="password" required />
    </div>
    <!-- <p id="message"></p> -->
    <?php if (!empty($errorMessage)): ?>
        <p style="color:red" class="error" id="message"><?= htmlspecialchars($errorMessage) ?></p>
    <?php endif; ?>
    <button type="submit" class="btn">
        Créer un compte
    </button>
</form>
<p>
    <a href="login">J'ai déjà un compte</a>
</p>
</div>
