<div class="center-container">
<h1>Créer un compte</h1>
<form id="signupForm" method="POST">
    <div>
        <label for="last_name">Votre nom</label>
        <input type="text" id="last_name" name="last_name" required />
    </div>
    <div>
        <label for="name">Votre prénom</label>
        <input type="text" id="name" name="name" required />
    </div>
    <div>
        <label for="email">Votre email</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="password">Votre mot de passe</label>
        <input type="password" id="password" name="password" required />
    </div>
    <p id="message"></p>
    <button type="submit" class="btn">
        Créer un compte
    </button>
</form>
<p>
    <a href="http://localhost/cup_of_tea_php/login">J'ai déjà un compte</a>
</p>
</div>
