<section id="product">
    <section id="product-detail">
        <div id="product-name">
            <h1><?= htmlspecialchars($tea['name']) ?></h1>
            <h2><?= htmlspecialchars($tea['subtitle']) ?></h2>
            <p>Ref : <?= htmlspecialchars($tea['reference']) ?></p>
        </div>
    </section>
    <section id="product-quantity">
        <img src="public/img/<?= htmlspecialchars($tea['image']) ?>" alt="<?= htmlspecialchars($tea['name']) ?>" />
        <div class="price">
            <select id="format-select" name="format" onchange="updatePriceFromFormat()">
                <?php 
                $index = 0;
                foreach ($formats as $format): ?>
                    <option value=<?= $index ?>><?= htmlspecialchars($format['conditioning']) ?></option>
                <?php $index++; endforeach; ?>
            </select>
            <h3 id="format-price"><?= htmlspecialchars(number_format($formats[0]['price'], 2)) ?>€</h3>
            <button class="btn" onclick="addToCart()">Ajouter au panier</button>
            <a id="wishlist" href="#">Ajouter à ma liste d'envie</a>
        </div>
    </section>
    <section id="product-description"><?= $tea['description'] ?></section>
</section>

<input type="hidden" id="tea-id" value="<?= htmlspecialchars($tea['id']) ?>">
<input type="hidden" id="formats" value="<?= htmlspecialchars(json_encode($formats)) ?>">
<script src="public/js/tea.js"></script>