<section id="product">
    <section id="product-detail">
        <div id="product-name">
            <h1><?= htmlspecialchars($tea['name']) ?></h1>
            <h2><?= htmlspecialchars($tea['subtitle']) ?></h2>
            <p>Ref : <?= htmlspecialchars($tea['reference']) ?></p>
        </div>
    </section>
    <section id="product-quantity">
        <img src="public/img/tea/<?= htmlspecialchars($tea['category_id']) ?>" alt="<?= htmlspecialchars($tea['name']) ?>" />
        <!-- <img src="public/img/tea/1.jpg" /> -->
        <div class="price">
            <select name="quantity">
                <?php foreach ($formats as $format): ?>
                    <option data-price="<?= htmlspecialchars($format['price']) ?>"><?= htmlspecialchars($format['conditioning']) ?></option>
                <?php endforeach; ?>
            </select>
            <!-- TODO : rendre dynamique avec AJAX  quand une autre option est sélectionnée ? -->
            <h3><?= htmlspecialchars(number_format($formats[0]['price'], 2)) ?>€</h3>
            <a class="btn" href="#">Ajouter au panier</a>
            <a id="wishlist" href="#">Ajouter à ma liste d'envie</a>
        </div>
    </section>
    <section id="product-description"><?= $tea['description'] ?></section>
</section>





<!--

<section id="product">
    <section id="product-detail">
        <div id="product-name">
            <h1>{ tea.nom }</h1>
            <h2>{ tea.sous_titre }</h2>
            <p>Ref : { tea.ref }</p>
        </div>

    </section>
    <section id="product-quantity">
        #<img src={ "/img/" + tea.image } alt={ tea.nom }
        <img src="public/img/tea/1.jpg" />
        <div class="price">
            <select value={cond} name="quantity" onChange={change}>
                { format.map((form, i ) => <option onClick={changePrice} data-price={form.prix} key={i}>{ form.conditionnement }</option>) }
            </select>
            <h3>{ price.toFixed(2) }€</h3>
            <a class="btn" onClick={add} href="#">Ajouter au panier</a>
            <a id="wishlist" href="#">Ajouter à ma liste d'envie</a>
        </div>
    </section>
    <section id="product-description" dangerouslySetInnerHTML={{__html:tea.description}} />

</section>

-->