<?php foreach ($cats as $cat): ?>
    <section class="tea">
        <img src="public/img/tea/<?= htmlspecialchars($cat['id']) ?>" alt="<?= htmlspecialchars($cat['name']) ?>" />
        <h2><span><?= htmlspecialchars($cat['name']) ?></span></h2>
        <p class="clear"><?= htmlspecialchars($cat['description']) ?></p>
        <section class="listing-product">
            <?php foreach ($teas as $tea): ?>
                <?php if ($tea['category_id'] == $cat['id']): ?>
                    <article>
                        <h3><?= htmlspecialchars($tea['name']) ?></h3>
                        <!-- <img src="public/img/tea/<?= htmlspecialchars($tea['category_id']) ?>" alt="<?= htmlspecialchars($tea['name']) ?>" /> -->
                        <img src="public/img/product/<?= htmlspecialchars($tea['image']) ?>" alt="<?= htmlspecialchars($tea['name']) ?>" />
                        <section class="price">
                            <p>À partir de <strong><?= htmlspecialchars($tea['price']) ?> €</strong></p>
                        </section>
                        <a class="btn" href="http://localhost/cup_of_tea_php/?route=tea&id=<?= $tea['id'] ?>">Voir ce produit</a>
                    </article>
                <?php endif; ?>
            <?php endforeach; ?>
        </section>
    </section>
<?php endforeach; ?>