
<?php if (empty($cart)): ?>
    <table id="cart-table">
        <thead>
            <tr>
                <th></th>
                <th>Produit</th>
                <th>Format</th>
                <th>Quantité</th>
                <th>Prix Unit.</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total = 0;
            $index = 0;
            foreach ($cart as $teaId => $tea):
                foreach ($tea['formats'] as $formatId => $format): ?>
                    <tr>
                        <td><?= ++$index ?></td>
                        <td><?= htmlspecialchars($tea['name']) ?></td>
                        <td><?= htmlspecialchars($format['format']) ?></td>
                        <td>
                            <select name="quantity-select" onchange="changeQuantity(<?= $teaId ?>, <?= $formatId ?>, this.value)">
                                <?php for($i = 1; $i <= 10; $i++): ?>
                                    <option value="<?= $i ?>" <?= $i == $format['quantity'] ? 'selected' : '' ?>><?= $i ?></option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td><?= number_format($format['price'], 2) ?>€</td>
                        <td><?= number_format($format['quantity'] * $format['price'], 2) ?>€</td>
                        <td><button class="btn grey-btn" onclick="changeQuantity(<?= $teaId ?>, <?= $formatId ?>, 0)">X</button></td>
                    </tr>
                    <?php 
                    $total += $format['price'] * $format['quantity'];
                endforeach;
            endforeach; ?>
        </tbody>
        <tfoot>
            <tr class='total'>
                <td colspan='5'></td>
                <td><?= number_format($total, 2) ?>€</td>
            </tr>
        </tfoot>
    </table>
<?php endif; ?>
